leaffrog/leaffrog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from leaffrog import settings
from shop.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = 'Админ панель моего проекта'
admin.site.index_title = 'Товары'

leaffrog/shop/urls.py
from django.urls import path, register_converter
from . import views
from . import converters


register_converter(converters.FourDigitConverter, 'year4')

urlpatterns = [
    path('', views.LeafFrogHome.as_view(), name='shop'),
    path('archive/<year4:year>/', views.archive), # бесполезный путь для демонстрации конвертора
    #path('registering/', views.Register.as_view(), name='reg'),
    path('product/<int:product_id>/', views.Product.as_view(), name='product'),
    path('catalog/<slug:cat_slug>/', views.CatalogSlug.as_view(), name='catalog_slug'),
    path('catalog/', views.Catalog.as_view(), name='catalog'),
    path('add_product/', views.add_product, name='add_product'),

]

leaffrog/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetCompleteView, PasswordResetConfirmView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('cart/', views.cart, name='cart'),
    path('favourites/', views.favourites, name='favourites'),
    path('registering/', views.RegisterUser.as_view(), name='reg'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditUser.as_view(), name='profile_edit'),
    path('profile/edit/password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('profile/edit/password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                   email_template_name='users/password_reset_email.html',
                                   success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

leaffrog/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db import models
from transliterate import slugify

from shop.models import Goods


class User(AbstractUser):
    class Sex(models.IntegerChoices):
        MALE = 0, 'Мужской'
        FEMALE = 1, 'Женский'

    class Seller(models.IntegerChoices):
        USER = 0, 'Пользователь'
        SELLER = 1, 'Продавец'

    sex = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Sex.choices)),
                                       default=True, verbose_name='Пол')
    city = models.ForeignKey('City', on_delete=models.SET_NULL, null=True, related_name='user', verbose_name='Город')
    seller = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Seller.choices)), default=False,
                                 blank=True)
    orders = models.ManyToManyField(Goods, blank=True, related_name='orders')
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True, null=True, verbose_name='Фотография')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class City(models.Model):
    city = models.CharField(max_length=255, db_index=True, verbose_name='Город')
    slug = models.SlugField(max_length=255, blank=True, verbose_name='Слаг')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.city)
        super(City, self).save(*args, **kwargs)

    def __str__(self):
        return self.city

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

leaffrog/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError

from users.models import City, User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(), label='Логин или Email', min_length=3)
    password = forms.CharField(widget=forms.PasswordInput(), label='Пароль', min_length=4)

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):
    GENDER_CHOICES = (
        ('0', 'Мужской'),
        ('1', 'Женский'),
    )

    username = forms.CharField(label='Логин', widget=forms.TextInput())
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повторите', widget=forms.PasswordInput())
    sex = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect, label='Пол: ')
    city = forms.ModelChoiceField(queryset=City.objects.all(), empty_label='Город не выбран', label='Город:')
    agree = forms.CharField(required=False)

    def clean_agree(self):
        agree = self.cleaned_data['agree']
        if not agree:
            raise ValidationError('Нужно принять соглашение')

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой Email уже существует')
        return email

    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     if get_user_model().objects.filter(username=username).exists():
    #         raise forms.ValidationError('Такой Логин уже существует')
    #     return username

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'sex', 'city', 'password1', 'password2', 'email']

        labels = {
            'first_name': 'Имя: ',
            'last_name': 'Фамилия: ',
            'sex': 'Пол: ',
            'password': 'Пароль: ',
            'email': 'Email: '
        }


class ProfileEditForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(), min_length=3, required=False, disabled=True)
    email = forms.CharField(label='Email', widget=forms.EmailInput(), required=False, disabled=True)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'photo']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

        widgets = {
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput()
        }

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     if email and get_user_model().objects.filter(email=email).exists():
    #         raise forms.ValidationError('Такой Email уже существует')
    #     return email
    #
    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     if username and get_user_model().objects.filter(username=username).exists():
    #         raise forms.ValidationError('Такой Логин уже существует')
    #     return username


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput())
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput())

leaffrog/users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, CreateView, DetailView, UpdateView

from leaffrog import settings
from users.forms import LoginUserForm, RegistrationForm, ProfileEditForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'

    # def get_success_url(self):
    #     return reverse_lazy('shop')


# def login_user(request):
#     if request.method == 'POST':
#         form = LoginUserForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('shop'))
#     else:
#         form = LoginUserForm()
#
#     return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


def favourites(request):
    return HttpResponseRedirect(reverse('shop'))


def cart(request):
    return HttpResponseRedirect(reverse('shop'))


def profile(request):
    return HttpResponseRedirect(reverse('shop'))


class RegisterUser(CreateView):
    form_class = RegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('shop')


class ProfileUser(LoginRequiredMixin, DetailView):
    template_name = 'users/profile.html'
    context_object_name = 'profile_data'
    extra_context = {
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        if user.seller is True:
            context['menu'] = [
                {'title': 'Добавить товар', 'url_name': 'add_product'},
                {'title': 'Мои товары', 'url_name': 'users:cart'},
                {'title': 'Избранное', 'url_name': 'users:login'},
                {'title': 'Заказы', 'url_name': 'catalog'},
                {'title': 'Изменить', 'url_name': 'users:profile_edit'},
                {'title': 'Выйти', 'url_name': 'users:logout'},
            ]
        else:
            context['menu'] = [
                {'title': 'Главная', 'url_name': 'shop'},
                {'title': 'Избранное', 'url_name': 'users:login'},
                {'title': 'Заказы', 'url_name': 'catalog'},
                {'title': 'Изменить', 'url_name': 'users:profile_edit'},
                {'title': 'Выйти', 'url_name': 'users:logout'},
            ]

        context['data'] = [
                {'title': 'Логин', 'value': user.username},
                {'title': 'Имя', 'value': user.first_name},
                {'title': 'Фамилия', 'value': user.last_name},
                {'title': 'Email', 'value': user.email},
                {'title': 'Город', 'value': user.city},
                {'title': 'Статус', 'value': user.seller},
            ]

        return context


class ProfileEditUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileEditForm
    template_name = 'users/profile_edit.html'
    extra_context = {
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        if user.seller is True:
            context['menu'] = [
                {'title': 'Добавить товар', 'url_name': 'add_product'},
                {'title': 'Мои товары', 'url_name': 'users:cart'},
                {'title': 'Избранное', 'url_name': 'users:login'},
                {'title': 'Заказы', 'url_name': 'catalog'},
                {'title': 'Изменить', 'url_name': 'users:profile_edit'},
                {'title': 'Выйти', 'url_name': 'users:logout'},

            ]
        else:
            context['menu'] = [
                {'title': 'Главная', 'url_name': 'shop'},
                {'title': 'Избранное', 'url_name': 'users:login'},
                {'title': 'Заказы', 'url_name': 'catalog'},
                {'title': 'Изменить', 'url_name': 'users:profile_edit'},
                {'title': 'Выйти', 'url_name': 'users:logout'},
            ]

        context['data'] = [
                {'title': 'Логин', 'value': user.username},
                {'title': 'Имя', 'value': user.first_name},
                {'title': 'Фамилия', 'value': user.last_name},
                {'title': 'Email', 'value': user.email},
                {'title': 'Город', 'value': user.city},
                {'title': 'Статус', 'value': user.seller},
            ]

        return context


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"

leaffrog/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
        <title>Вход</title>
        <meta charset="utf-8" http-equiv="Content-Type" content="text/html">
        <link rel="stylesheet" href="{% static 'users/css/login.css' %}">
    </head>
<body>



    <div class="login-box">  
          <div class="header-logo">

        <a class="nav-item" href="{% url 'shop' %}"><img src="{% static 'shop/images/logo.svg' %}" alt="" width="120"></a>




    </div>
        <h2>Авторизация</h2>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}

                <label for="{{ f.id_for_label }}">
                <div class="user-box">
                    {{ f }}
                    <label>{{ f.label }}</label>
                </div>
                    </label>
                    <div class="form-error">{{ f.errors }}</div>

            {% endfor %}




            <button type="submit" class="btn">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Войти
            </button>

            <a class="btn" href="{% url 'users:password_reset' %}"> Забыли пароль?</a>
        </form>
          <a class="nav-item" href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.png" alt="" width="50"></a>
          <a class="nav-item" href="{% url 'social:begin' 'vk-oauth2' %}"><img src="/media/social-auth/VK.png" alt="" width="50"></a>

    </div>



</body>
</html>

leaffrog/users/templates/users/password_change_done.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}

<div class="col3">
                <div class="card55">
                    <h1 class="bbb ">Пароль успешно изменен!</h1>
                    <div class="card-bod">

                            <p class="im">
                                <a href="{% url 'shop' %}"><button class="inp" type="submit">Магазин</button></a></p>
                            <p class="im">
                                <a href="{% url 'users:profile' %}"><button class="inp" type="submit">Профиль</button></a></p>


                        </form>
                    </div>
                </div>
                </div>

{% endblock %}

leaffrog/users/templates/users/password_change_form.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}

<div class="col3">
                <div class="card55">
                    <h1 class="bbb ">Изменение пароля</h1>
                    <div class="card-bod">
                        <form action="" method="post" enctype="multipart/form-data" class="contact-left">
                        {% csrf_token %}
                            <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}


                        <div class="row">
                            <div class="nam">
                                <label for="{{ f.id_for_label }}">
                                <h5>{{ f.label }}</h5></label>
                            </div>
                            <div class="nam1">
                                {{ f }}

                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% if not forloop.last %} <hr> {% endif %}

                        {% endfor %}
                            <p class="im"><button class="inp" type="submit">Обновить</button> </p>
                        </form>
                </div>
                </div>
                </div>

{% endblock %}

leaffrog/users/templates/users/password_reset_complete.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}

<div class="col3">
                <div class="card55">
                    <h1 class="bbb ">Пароль успешно изменен</h1>
                    <div class="card-bod">
                        <form action="" method="post" enctype="multipart/form-data" class="contact-left">
                        {% csrf_token %}
                            <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}


                        <div class="row">
                            <div class="nam">
                                <label for="{{ f.id_for_label }}">
                                <h5>{{ f.label }}</h5></label>
                            </div>
                            <div class="nam1">
                                {{ f }}

                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% if not forloop.last %} <hr> {% endif %}

                        {% endfor %}
                        </form>
                        <p class="im"><a href="{% url 'users:login' %}"> <button class="inp">Войти</button> </a></p>
                    </div>
                </div>
                </div>

{% endblock %}

leaffrog/users/templates/users/password_reset_confirm.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}

<div class="col3">
                <div class="card55">
                    <h1 class="bbb ">Новый пароль</h1>
                    <div class="card-bod">
                        <form action="" method="post" enctype="multipart/form-data" class="contact-left">
                        {% csrf_token %}
                            <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}


                        <div class="row">
                            <div class="nam">
                                <label for="{{ f.id_for_label }}">
                                <h5>{{ f.label }}</h5></label>
                            </div>
                            <div class="nam1">
                                {{ f }}

                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% if not forloop.last %} <hr> {% endif %}

                        {% endfor %}
                            <p class="im"><button class="inp" type="submit">Сохранить</button> </p>
                        </form>
                </div>
                </div>
                </div>

{% endblock %}

leaffrog/users/templates/users/password_reset_done.html
{% extends 'header.html' %}
{% load i18n %}

{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}

{% block content %}
{% load static %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

leaffrog/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

leaffrog/users/templates/users/password_reset_form.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}

<div class="col3">
                <div class="card55">
                    <h1 class="bbb ">Восстановление пароля</h1>
                    <div class="card-bod">
                        <form action="" method="post" enctype="multipart/form-data" class="contact-left">
                        {% csrf_token %}
                            <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}


                        <div class="row">
                            <div class="nam">
                                <label for="{{ f.id_for_label }}">
                                <h5>{{ f.label }}</h5></label>
                            </div>
                            <div class="nam1">
                                {{ f }}

                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% if not forloop.last %} <hr> {% endif %}

                        {% endfor %}
                            <p class="im"><button class="inp" type="submit">Восстановить</button> </p>
                        </form>
                </div>
                </div>
                </div>

{% endblock %}

leaffrog/users/templates/users/profile.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}




<div class="container">
    <div class="main">
        <div class="row">
            <div class="col">
                <div class="ca ">
                    <div class="car-body">
                        <div class="img">
                            {% if user.photo %}
                                <img src="{{ user.photo.url }}" class="imgs" width="150">
                            {% else %}
                                <img src="{{ default_image }}" class="imgs" width="150">
                            {% endif %}
                        </div>
                        <div class="menu">
                            <h3>{{ user.first_name }} {{ user.last_name }}</h3>
                            {% for m in menu %}
                            <a href="{% url m.url_name %}">{{ m.title }}</a>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>


            <div class="col2">
                <div class="card55">
                    <h1 class="bbb ">Основная информация</h1>
                    <div class="card-bod">
                        {% for d in data %}


                        <div class="row">
                            <div class="nam">
                                <h5>{{ d.title }}</h5>
                            </div>
                            <div class="nam1">
                                {% if d.title == 'Статус' %}
                                    {{ d.value|yesno:"Продавец,Пользователь" }}
                                {% else %}
                                    {{ d.value }}
                                {% endif %}
                            </div>
                        </div>
                        {% if not forloop.last %} <hr> {% endif %}

                        {% endfor %}
                    </div>
                </div>

                
        </div>
    </div>

</div>
</div>

{% endblock %}

leaffrog/users/templates/users/profile_edit.html
{% extends 'header.html' %}


{% block add_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}


{% block content %}
{% load static %}




<div class="container">
    <div class="main">
        <div class="row">
            <div class="col">
                <div class="ca ">
                    <div class="car-body">
                        <div class="img">
                            {% if user.photo %}
                                <img src="{{ user.photo.url }}" class="imgs" width="150">
                            {% else %}
                                <img src="{{ default_image }}" class="imgs" width="150">
                            {% endif %}
                        </div>
                        <div class="menu">
                            <h3>{{ user.first_name }} {{ user.last_name }}</h3>
                            {% for m in menu %}
                            <a href="{% url m.url_name %}">{{ m.title }}</a>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>


            <div class="col2">
                <div class="card55">
                    <h1 class="bbb ">Изменить основную информацию</h1>
                    <div class="card-bod">
                        <form action="" method="post" enctype="multipart/form-data" class="contact-left">
                        {% csrf_token %}
                            <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}


                        <div class="row">
                            <div class="nam">
                                <label for="{{ f.id_for_label }}">
                                <h5>{{ f.label }}</h5></label>
                            </div>
                            <div class="nam1">
                                {{ f }}

                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% if not forloop.last %} <hr> {% endif %}

                        {% endfor %}
                            <p class="im"><button class="inp" type="submit">Обновить</button> </p>
                        </form>

                            {% if not perms.users.social_auth or user.is_superuser%}
                            <div class="card55">
                                <h1 class="bbb ">Изменение пароля</h1>

                            <div class="nam5">
                                    <a class="psw" href="{% url 'users:password_change' %}">Изменить пароль</a>
                            </div>
                                </div>
                                </div>
                            {% endif %}




                    </div>
                </div>

                
        </div>
    </div>

</div>
</div>

{% endblock %}