leaffrog/leaffrog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from leaffrog import settings
from shop.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = 'Админ панель моего проекта'
admin.site.index_title = 'Товары'

leaffrog/shop/urls.py
from django.urls import path, register_converter
from . import views
from . import converters


register_converter(converters.FourDigitConverter, 'year4')

urlpatterns = [
    path('', views.LeafFrogHome.as_view(), name='shop'),
    path('archive/<year4:year>/', views.archive), # бесполезный путь для демонстрации конвертора
    #path('registering/', views.Register.as_view(), name='reg'),
    path('product/<int:product_id>/', views.Product.as_view(), name='product'),
    path('catalog/<slug:cat_slug>/', views.CatalogSlug.as_view(), name='catalog_slug'),
    path('catalog/', views.Catalog.as_view(), name='catalog'),
    path('add_product/', views.add_product, name='add_product'),

]

leaffrog/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetCompleteView, PasswordResetConfirmView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('cart/', views.cart, name='cart'),
    path('favourites/', views.favourites, name='favourites'),
    path('registering/', views.RegisterUser.as_view(), name='reg'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditUser.as_view(), name='profile_edit'),
    path('profile/edit/password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('profile/edit/password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                   email_template_name='users/password_reset_email.html',
                                   success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

leaffrog/templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block add_css %}

    {% endblock %}

    <link rel= "shortcut icon" href="{% static 'shop/images/logo.ico' %}" type="image/x-icon">
    <meta charset="utf-8" http-equiv="Content-Type" content="text/html">
    <link rel="stylesheet" href="{% static 'shop/css/index_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <title>MyShop (Beta)</title>
 </head>

<body>

<div class="header">
    <div class="container"> 
        <div class="header-line">
            <div class="header-logo">

                <a class="nav-item" href="{% url 'shop' %}"><img src="{% static 'shop/images/logo.svg' %}" alt="" width="120"><p>Leaf Frog</p></a>

            </div>
            <div class="">
                {% if user.is_authenticated %}

                    {% for m in menu_is_auth %}
                      {% if not forloop.last %}
                            <a class="nav-item" href="{% url m.url_name %}">{{ m.title }}</a>
                        {% else %}
                             <a class="nav-item" href="{% url 'users:profile' %}">{{ user.username }}</a> | <a class="button-exit" href="{% url m.url_name %}">{{ m.title }}</a>
                        {% endif %}
                    {% endfor %}
                {% else %}


                    {% for m in menu_not_auth %}
                        {% if not forloop.last %}
                            <a class="nav-item" href="{% url m.url_name %}">{{ m.title }}</a>
                        {% else %}
                            <a class="button" href="{% url m.url_name %}">{{ m.title }}</a>
                        {% endif %}

                    {% endfor %}

                {% endif %}

            </div>
        </div>
    </div>   
</div>

{% block content %}

{% endblock %}

</body>
</html>